"""
Generate outputs/<TICKER>/docs/sources_and_assumptions.md from companies/<TICKER>/source_register.csv,
assumptions_log.csv and reported_financials.csv, so the human-readable log can never drift from the files the model uses.
Run: python scripts/build_docs.py --company TICKER
Run: python scripts/build_docs.py
"""
import csv
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import engine  # noqa: E402
EN = engine.get()
reg = list(csv.DictReader(EN.source_register.open(encoding="utf-8")))
asm = list(csv.DictReader(EN.assumptions_log.open(encoding="utf-8")))
rep = list(csv.DictReader(EN.reported_csv.open(encoding="utf-8")))


def md(s):
    return str(s).replace("|", "/").replace("\n", " ")


lines = ["# Sources and assumptions log", "",
         "Generated by `scripts/build_docs.py` from the CSV files the model reads. Do not edit by hand.", "",
         "> " + EN.disclaimer, "",
         "## Value classification", "",
         "| Classification | Meaning | Where it lives |", "|---|---|---|",
         "| Reported public data | Transcribed from a " + EN.company["name"] + " SEC filing; source URL on every value | `companies/" + EN.ticker + "/reported_financials.csv`, Excel `Hist_Data` (blue) |",
         "| Calculated value | An Excel formula on other cells | Every black cell in the workbook |",
         "| User-provided assumption | A decision logged below with who made it | Excel `Assumptions`, `Capex` (blue / yellow) |",
         "| Simulated operational data | Invented division-level operating data, labeled on every tab | Excel `Assumptions` D, `Actuals` |", "",
         "## Source register", "",
         "| ID | Document | Accession no. | Covers | Used for |", "|---|---|---|---|---|"]
lines += [f"| {r['source_id']} | [{md(r['document'])}]({r['url']}) | {r['accession_no']} | {md(r['period_covered'])} | {md(r['used_for'])} |" for r in reg]
cnt = Counter(r["statement"] for r in rep)
lines += ["", f"### Reported values collected: {len(rep)}", "",
          "| Statement | Values |", "|---|---|"] + [f"| {k} | {v} |" for k, v in sorted(cnt.items())]
p0 = EN.tests / "phase0_validation_results.csv"
n0 = f"{sum(1 for _ in csv.DictReader(p0.open()))} " if p0.exists() else ""
lines += ["", f"Every row of `companies/{EN.ticker}/reported_financials.csv` carries the filing, accession number, statement page URL and "
              f"the label as printed. `tests/validate_reported_data.py` runs {n0}consistency and cross-filing checks on it.", "",
          "## Assumptions log", "", "| ID | Area | Assumption | Value | Classification | Decided by | Status |", "|---|---|---|---|---|---|---|"]
lines += [f"| {a['id']} | {md(a['area'])} | {md(a['assumption'])} | {md(a['value'])} | {md(a['classification'])} | {md(a['decided_by'])} | {md(a['status'])} |" for a in asm]
lines += ["", "Rationale for each assumption is in `companies/" + EN.ticker + "/assumptions_log.csv` (column `rationale`) and next to the input in the workbook."]
(EN.docs / "sources_and_assumptions.md").write_text("\n".join(lines) + "\n")
print(f"Wrote {(EN.docs / 'sources_and_assumptions.md').relative_to(ROOT)} ({len(reg)} sources, {len(asm)} assumptions, {len(rep)} reported values)")
